# 현재 Potainer에서 가장 최신 버전
# 더 많은 정보를 원할 경우에는 공식문서 참고
version: "3.7"
services:
  # 서비스 이름
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_1ban_network
    volumes:
      - gis_1ban_static:/data/static/
      - gis_1ban_media:/data/media/
      - /home/sjhge08/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django:
    image: gis_1ban_django:3
    networks:
      # 이름은 꼭 Potainer에서 생성한 것과 동일하지 않아도 됨
      - gis_1ban_network
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - gis_1ban_static:/home/gis_1ban_2/staticfiles/
      - gis_1ban_media:/home/gis_1ban_2/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_1ban_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    # 먼저 Potainer에서 Secret 생성 후 아래 문구 추가  + 가장 밑에 선언
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: 1q2w3e4r!
      MARIADB_ROOT_PASSWORD: 1q2w3e4r!

networks:
  gis_1ban_network:

volumes:
  gis_1ban_static:
  gis_1ban_media:
  gis_mariadb:

secrets:
  MARIADB_USER:
    # 우리가 Potainer에 Secret을 따로 만들어주었기 때문에 여기있는 이름과 그것들의 이름이 매칭되면 가져옴
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  DJANGO_SECRET_KEY:
    external: true